-- Allow creating AOPs by hand (Supabase Studio / SQL editor) without
-- providing every column.
--
-- `aop.id` was imported as a plain `integer primary key` carrying the comagri
-- IDA values (currently 1..2428). The column has no default, and `slug` is
-- NOT NULL UNIQUE with no default either, so any insert that omits them fails:
--   null value in column "id" of relation "aop" violates not-null constraint
--
-- This migration is idempotent and transactional: it is safe to paste into the
-- Supabase SQL editor and re-run if a previous run only partially applied.

begin;

-- ── 1. Auto-generate `id` when omitted ────────────────────────────────────────
-- BY DEFAULT (not ALWAYS) so the comagri import pipeline can keep inserting
-- explicit IDA ids. Guarded so re-running does not fail with
-- "column id of relation aop is already an identity column".
do $$
begin
  if not exists (
    select 1
      from pg_attribute
     where attrelid = 'public.aop'::regclass
       and attname  = 'id'
       and attidentity in ('a', 'd')  -- ALWAYS or BY DEFAULT
  ) then
    alter table public.aop
      alter column id add generated by default as identity;
  end if;
end $$;

-- Start generated ids at 100001, far above the comagri IDA range, so future
-- dataset imports (explicit ids) cannot collide with manually created rows.
-- Safe to re-run.
select setval(
  pg_get_serial_sequence('public.aop', 'id'),
  greatest(coalesce((select max(id) from public.aop), 0), 100000) + 1,
  false
);

-- ── 2. Auto-generate `slug` when omitted ──────────────────────────────────────
-- `slug` is NOT NULL UNIQUE with no default, so a manual insert would fail on
-- it right after `id`. Generate it from `name` with the same normalization as
-- the 20260416100000 backfill.
create extension if not exists unaccent;

create or replace function public.aop_fill_slug()
returns trigger
language plpgsql
set search_path = public, extensions
as $$
begin
  if new.slug is null or new.slug = '' then
    new.slug := trim(
      both '-' from
      regexp_replace(
        lower(unaccent(trim(new.name))),
        '[^a-z0-9]+', '-', 'g'
      )
    );
  end if;
  return new;
end;
$$;

drop trigger if exists aop_fill_slug on public.aop;
create trigger aop_fill_slug
  before insert on public.aop
  for each row execute function public.aop_fill_slug();

commit;
